---
apiVersion: v1
kind: Service
metadata:
  name: nodeexporter-nodeport-service
spec:
  selector:
      name: node-exporter
  type: NodePort
  ports:
    - port: 9100
      nodePort: 31500
      targetPort: 9100